source 'https://rubygems.org'
ruby "2.3.1"
gem 'execjs'
gem 'therubyracer'
gem 'github-pages'
gem 'jekyll-paginate'
gem 'kramdown'
gem 'rack-jekyll'
gem 'rake'
# gem 'puma'
gem 'rack-contrib'
gem 'puma'
# gem 'jekyll-archives'
